[package]
name = "routed_stake"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
royalty_pool = { git = "https://github.com/misonetwork/royalty-pool.git", rev = "8470e492252b56da563a5b251e204ee090149724" }
